[[redirects]]
  from = "http://localhost:3000/?q=t.json"
  to = "https://localweatherwatch.netlify.app/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"